#!/bin/bash

### BEGIN INIT INFO
# Provides:		atxpi-gpio-shutdown
# Required-Start:	$all
# Required-Stop:	$all
# Default-Start:	2 3 4 5
# Default-Stop:	0 1 6
# Short-Description: Shutdown if the chassis power button is pressed
### END INIT INFO

set -e
. /lib/lsb/init-functions

case $1 in
	start)
		/opt/atxpi/shutdown.sh &
	;;
esac

exit 0
